stages:
  - test

variables:
  PYTHONPATH: "$PYTHONPATH:."

test:
  stage: test
  image: python:3.11
  before_script:
    - pip install --upgrade pip --root-user-action=ignore
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
  script:
    - pytest tests/