stages:
  - test
  - build
  - deploy

variables:
  PYTHONPATH: "$PYTHONPATH:."
  DOCKER_DRIVER: overlay2

test:
  stage: test
  image: python:3.11
  before_script:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
  script:
    - pytest tests/

build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - docker login -u _ -p $HEROKU_API_KEY registry.heroku.com
  script:
    - docker build -t registry.heroku.com/stylusfusion/web .
    - docker push registry.heroku.com/stylusfusion/web

deploy:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - apt-get update
    - apt-get install -y curl
    - curl https://cli-assets.heroku.com/install.sh | sh
    - heroku container:login
  script:
    - heroku container:release web -a stylusfusion
  only:
    - main
