stages:
  - build
  - deploy

variables:
  PYTHONPATH: "$PYTHONPATH:."
  DOCKER_DRIVER: overlay2

build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  before_script:
    - docker login -u _ -p $HEROKU_API_KEY registry.heroku.com
  script:
    - docker build -t registry.heroku.com/stylusfusion/web .
    - docker push registry.heroku.com/stylusfusion/web

deploy:
  stage: deploy
  image: docker:stable-dind
  services:
    - docker:dind
  before_script:
    - apk add --no-cache bash curl
    - curl https://cli-assets.heroku.com/install.sh | sh
    - heroku container:login
  script:
    - heroku container:release web -a stylusfusion
  only:
    - main
