stages:
  - build
  - deploy

variables:
  PYTHONPATH: "$PYTHONPATH:."
  DOCKER_DRIVER: overlay2

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u _ -p $HEROKU_API_KEY registry.heroku.com
  script:
    - docker build -t registry.heroku.com/stylusfusion/web .
    - docker push registry.heroku.com/stylusfusion/web

deploy:
  stage: deploy
  image: ubuntu:latest
  services:
    - docker:dind
  before_script:
    - apt-get update
    - apt-get install -y curl
    - curl -fsSL https://get.docker.com -o get-docker.sh
    - sh get-docker.sh
    - service docker start
    - curl https://cli-assets.heroku.com/install.sh | sh
    - heroku container:login
  script:
    - heroku container:release web -a stylusfusion
  only:
    - main
